name: Test API & DB using Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DB_NAME: calculateur_moyennes
      DB_USER: testdb
      DB_PASSWORD: testdb

    services:
        db:
          image: mysql
          env:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: ${{ env.DB_NAME }}
            MYSQL_USER: ${{ env.DB_USER }}
            MYSQL_PASSWORD: ${{ env.DB_PASSWORD }}
          ports:
            - 3306:3306
          options: >-
            --health-cmd "mysqladmin ping"
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5
            --name db
            --hostname db

    steps:
      - uses: actions/checkout@v3
      - name: Init DB
        run: echo "USE $DB_NAME;" | cat - ./db/init.sql | mysql -h 127.0.0.1 -u$DB_USER -p$DB_PASSWORD
      - name: NPM install API
        run: cd api && npm install
      - name: Test api
        run: cd api && npm test
